
version: 1
jobs:
  build:  
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: scripts/install.ios.sh
      - run:
          name: npm install
          command: npm install
      - run:
          name: Detox iOS CI
          command: 'npm run test-e2e-ios-release'