
version: 2
jobs:
  build:  
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: scripts/install.ios.sh
      - run:
          name: Install Android
          command: scripts/install.android.sh
      - run:
          name: npm install
          command: npm install
  test:
    macos:
      xcode: "10.2.1"
      parallelism: 3
    steps:
      - run:
          name: iOS unit tests
          command: 'npm run test-unit-ios'
      - run:
          name: Android unit tests
          command: 'npm run test-unit-android'
      - run:
          name: Detox iOS CI
          command: 'npm run test-e2e-ios-release'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test